<template>
	<div class="notebook">
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
        <p>Culpa labore cupidatat in proident quis eiusmod commodo veniam. Laborum consequat ut aliquip laborum. Ea duis voluptate quis in officia in. Aliquip culpa quis veniam id ex do minim ex eu ipsum ex irure duis ipsum. Aute nisi magna esse incididunt fugiat sit occaecat amet ex.</p>
	</div>
</template>

<script>
import "@/styles/notebook.css";

export default {
	name: "NoteBook",
};
</script>
